---
- name: Ansible with one module
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Welcome friends
      set_fact:
        result:
          message: "Hello Ansible"

    - name: Show message
      debug:
        msg: "{{ result.message }}"
